[MQTT]
host=${config.UCL.ip|192.168.1.80}
port=1883
username=░░░░░░░░
password=░░░░░░░░
cleanSession=0
clientId=Furamel${@getClientId}

[topic]
command=EDGE/${var.struttura}/DM/CMD/${config.UCL.nome}
feedback=EDGE/${var.struttura}/DM/CMD/FEEDBACK/${config.UCL.nome}
status=EDGE/${var.struttura}/DM/STATUS/${config.UCL.nome}
settings=${config.UCL.nome}/settings/
settingsResponse=${config.UCL.nome}/settingsResponse/
allerts=allerts/

; Questa sezione sarà ignorata se c'è var/envConfig.json
[UCL]
ip=192.168.1.80
struttura=""
nome=ucl_name
id=000000000
idStruttura=00000000

[var]
gateway=${par.devId||config.UCL.idStruttura||request.clientId}_${par.type|UCL}
struttura=${config.UCL.struttura|non-presente}
